"""create formatting profiles and jobs tables

Revision ID: cbfceb0c03a8
Revises: f090d0f39212
Create Date: 2026-07-18 10:38:30.209304

"""
import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbfceb0c03a8'
down_revision: str | Sequence[str] | None = 'f090d0f39212'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

GOST_PROFILE_ID = uuid.UUID("11111111-1111-1111-1111-111111111111")

formatting_profiles_table = sa.table(
    "formatting_profiles",
    sa.column("id", postgresql.UUID(as_uuid=True)),
    sa.column("owner_id", postgresql.UUID(as_uuid=True)),
    sa.column("name", sa.String),
    sa.column("rules", postgresql.JSONB),
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formatting_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'failed', name='job_status'), nullable=False),
    sa.Column('input_file', sa.String(length=255), nullable=False),
    sa.Column('output_file', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['formatting_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###

    op.bulk_insert(
        formatting_profiles_table,
        [
            {
                "id": GOST_PROFILE_ID,
                "owner_id": None,
                "name": "ГОСТ 7.32-2017",
                "rules": {
                    "font_family": "Times New Roman",
                    "font_size_pt": 14,
                    "line_spacing": 1.5,
                    "margins_mm": {"top": 20, "bottom": 20, "left": 30, "right": 15},
                },
            }
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('formatting_profiles')
    # ### end Alembic commands ###
